const data = {
    name: "tableOne",
    code: "designer",
    body: [
            {
                id: 0,
                columnDataField: "data",
                columnCaption: "caption One",
                columnDataType: "dataType",
                columnFormat: "format",
                columnAlignment: "center",
                items: [
                    {id:1, rowDataField:"data", rowCaption:"row_1", rowFormat: "format"},
                    {id:2, rowDataField:"data", rowCaption:"row_2", rowFormat: "format"},
                    {id:3, rowDataField:"data", rowCaption:"row_3", rowFormat: "format"},
                    {id:4, rowDataField:"data", rowCaption:"row_4", rowFormat: "format"},
                    {id:5, rowDataField:"data", rowCaption:"row_5", rowFormat: "format"},
                    {id:6, rowDataField:"data", rowCaption:"row_6", rowFormat: "format"},
                    {id:7, rowDataField:"data", rowCaption:"row_7", rowFormat: "format"},
                    {id:8, rowDataField:"data", rowCaption:"row_8", rowFormat: "format"},
                    {id:9, rowDataField:"data", rowCaption:"row_9", rowFormat: "format"},
                    {id:10, rowDataField:"data", rowCaption:"row_10", rowFormat: "format"},
                    {id:11, rowDataField:"data", rowCaption:"row_11", rowFormat: "format"},
                    {id:12, rowDataField:"data", rowCaption:"row_12", rowFormat: "format"},
                    {id:13, rowDataField:"data", rowCaption:"row_13", rowFormat: "format"},
                    {id:14, rowDataField:"data", rowCaption:"row_14", rowFormat: "format"},
                    {id:15, rowDataField:"data", rowCaption:"row_15", rowFormat: "format"},
                    {id:16, rowDataField:"data", rowCaption:"row_16", rowFormat: "format"},
                    {id:17, rowDataField:"data", rowCaption:"row_17", rowFormat: "format"},
                    {id:18, rowDataField:"data", rowCaption:"row_18", rowFormat: "format"},
                    {id:19, rowDataField:"data", rowCaption:"row_19", rowFormat: "format"},
                    {id:20, rowDataField:"data", rowCaption:"row_20", rowFormat: "format"},
                    {id:21, rowDataField:"data", rowCaption:"row_21", rowFormat: "format"},
                    {id:22, rowDataField:"data", rowCaption:"row_22", rowFormat: "format"},
                    {id:23, rowDataField:"data", rowCaption:"row_23", rowFormat: "format"},
                    {id:24, rowDataField:"data", rowCaption:"row_24", rowFormat: "format"},
                    {id:25, rowDataField:"data", rowCaption:"row_25", rowFormat: "format"},
                    {id:26, rowDataField:"data", rowCaption:"row_26", rowFormat: "format"},
                    {id:27, rowDataField:"data", rowCaption:"row_27", rowFormat: "format"},
                    {id:28, rowDataField:"data", rowCaption:"row_28", rowFormat: "format"},
                    {id:29, rowDataField:"data", rowCaption:"row_29", rowFormat: "format"},
                    {id:30, rowDataField:"data", rowCaption:"row_30", rowFormat: "format"},
                    {id:31, rowDataField:"data", rowCaption:"row_31", rowFormat: "format"},
                    {id:32, rowDataField:"data", rowCaption:"row_32", rowFormat: "format"},
                    {id:33, rowDataField:"data", rowCaption:"row_33", rowFormat: "format"},
                    {id:34, rowDataField:"data", rowCaption:"row_34", rowFormat: "format"},
                    {id:35, rowDataField:"data", rowCaption:"row_35", rowFormat: "format"},
                    {id:36, rowDataField:"data", rowCaption:"row_36", rowFormat: "format"},
                    {id:37, rowDataField:"data", rowCaption:"row_37", rowFormat: "format"},
                    {id:38, rowDataField:"data", rowCaption:"row_38", rowFormat: "format"},
                    {id:39, rowDataField:"data", rowCaption:"row_39", rowFormat: "format"},
                    {id:40, rowDataField:"data", rowCaption:"row_40", rowFormat: "format"},
                    {id:41, rowDataField:"data", rowCaption:"row_41", rowFormat: "format"},
                    {id:42, rowDataField:"data", rowCaption:"row_42", rowFormat: "format"}
                    ]
            },
        {
                id: 1,
                columnDataField: "data",
                columnCaption: "caption Two",
                columnDataType: "dataType",
                columnFormat: "format",
                columnAlignment: "center",
                items: [
                    {id:1, rowDataField:"data", rowCaption:"row_1", rowFormat: "format"},
                    {id:2, rowDataField:"data", rowCaption:"row_2", rowFormat: "format"},
                    {id:3, rowDataField:"data", rowCaption:"row_3", rowFormat: "format"},
                    {id:4, rowDataField:"data", rowCaption:"row_4", rowFormat: "format"},
                    {id:5, rowDataField:"data", rowCaption:"row_5", rowFormat: "format"},
                    {id:6, rowDataField:"data", rowCaption:"row_6", rowFormat: "format"},
                    {id:7, rowDataField:"data", rowCaption:"row_7", rowFormat: "format"},
                    {id:8, rowDataField:"data", rowCaption:"row_8", rowFormat: "format"},
                    {id:9, rowDataField:"data", rowCaption:"row_9", rowFormat: "format"},
                    {id:10, rowDataField:"data", rowCaption:"row_10", rowFormat: "format"},
                    {id:11, rowDataField:"data", rowCaption:"row_11", rowFormat: "format"},
                    {id:12, rowDataField:"data", rowCaption:"row_12", rowFormat: "format"},
                    {id:13, rowDataField:"data", rowCaption:"row_13", rowFormat: "format"},
                    {id:14, rowDataField:"data", rowCaption:"row_14", rowFormat: "format"},
                    {id:15, rowDataField:"data", rowCaption:"row_15", rowFormat: "format"},
                    {id:16, rowDataField:"data", rowCaption:"row_16", rowFormat: "format"},
                    {id:17, rowDataField:"data", rowCaption:"row_17", rowFormat: "format"},
                    {id:18, rowDataField:"data", rowCaption:"row_18", rowFormat: "format"},
                    {id:19, rowDataField:"data", rowCaption:"row_19", rowFormat: "format"},
                    {id:20, rowDataField:"data", rowCaption:"row_20", rowFormat: "format"},
                    {id:21, rowDataField:"data", rowCaption:"row_21", rowFormat: "format"},
                    {id:22, rowDataField:"data", rowCaption:"row_22", rowFormat: "format"},
                    {id:23, rowDataField:"data", rowCaption:"row_23", rowFormat: "format"},
                    {id:24, rowDataField:"data", rowCaption:"row_24", rowFormat: "format"},
                    {id:25, rowDataField:"data", rowCaption:"row_25", rowFormat: "format"},
                    {id:26, rowDataField:"data", rowCaption:"row_26", rowFormat: "format"},
                    {id:27, rowDataField:"data", rowCaption:"row_27", rowFormat: "format"},
                    {id:28, rowDataField:"data", rowCaption:"row_28", rowFormat: "format"},
                    {id:29, rowDataField:"data", rowCaption:"row_29", rowFormat: "format"},
                    {id:30, rowDataField:"data", rowCaption:"row_30", rowFormat: "format"},
                    {id:31, rowDataField:"data", rowCaption:"row_31", rowFormat: "format"},
                    {id:32, rowDataField:"data", rowCaption:"row_32", rowFormat: "format"},
                    {id:33, rowDataField:"data", rowCaption:"row_33", rowFormat: "format"},
                    {id:34, rowDataField:"data", rowCaption:"row_34", rowFormat: "format"},
                    {id:35, rowDataField:"data", rowCaption:"row_35", rowFormat: "format"},
                    {id:36, rowDataField:"data", rowCaption:"row_36", rowFormat: "format"},
                    {id:37, rowDataField:"data", rowCaption:"row_37", rowFormat: "format"},
                    {id:38, rowDataField:"data", rowCaption:"row_38", rowFormat: "format"},
                    {id:39, rowDataField:"data", rowCaption:"row_39", rowFormat: "format"},
                    {id:40, rowDataField:"data", rowCaption:"row_40", rowFormat: "format"},
                    {id:41, rowDataField:"data", rowCaption:"row_41", rowFormat: "format"},
                    {id:42, rowDataField:"data", rowCaption:"row_42", rowFormat: "format"}
                    ]
            },
{
                id: 2,
                columnDataField: "data",
                columnCaption: "caption Three",
                columnDataType: "dataType",
                columnFormat: "format",
                columnAlignment: "center",
                items: [
                    {id:1, rowDataField:"data", rowCaption:"row_1", rowFormat: "format"},
                    {id:2, rowDataField:"data", rowCaption:"row_2", rowFormat: "format"},
                    {id:3, rowDataField:"data", rowCaption:"row_3", rowFormat: "format"},
                    {id:4, rowDataField:"data", rowCaption:"row_4", rowFormat: "format"},
                    {id:5, rowDataField:"data", rowCaption:"row_5", rowFormat: "format"},
                    {id:6, rowDataField:"data", rowCaption:"row_6", rowFormat: "format"},
                    {id:7, rowDataField:"data", rowCaption:"row_7", rowFormat: "format"},
                    {id:8, rowDataField:"data", rowCaption:"row_8", rowFormat: "format"},
                    {id:9, rowDataField:"data", rowCaption:"row_9", rowFormat: "format"},
                    {id:10, rowDataField:"data", rowCaption:"row_10", rowFormat: "format"},
                    {id:11, rowDataField:"data", rowCaption:"row_11", rowFormat: "format"},
                    {id:12, rowDataField:"data", rowCaption:"row_12", rowFormat: "format"},
                    {id:13, rowDataField:"data", rowCaption:"row_13", rowFormat: "format"},
                    {id:14, rowDataField:"data", rowCaption:"row_14", rowFormat: "format"},
                    {id:15, rowDataField:"data", rowCaption:"row_15", rowFormat: "format"},
                    {id:16, rowDataField:"data", rowCaption:"row_16", rowFormat: "format"},
                    {id:17, rowDataField:"data", rowCaption:"row_17", rowFormat: "format"},
                    {id:18, rowDataField:"data", rowCaption:"row_18", rowFormat: "format"},
                    {id:19, rowDataField:"data", rowCaption:"row_19", rowFormat: "format"},
                    {id:20, rowDataField:"data", rowCaption:"row_20", rowFormat: "format"},
                    {id:21, rowDataField:"data", rowCaption:"row_21", rowFormat: "format"},
                    {id:22, rowDataField:"data", rowCaption:"row_22", rowFormat: "format"},
                    {id:23, rowDataField:"data", rowCaption:"row_23", rowFormat: "format"},
                    {id:24, rowDataField:"data", rowCaption:"row_24", rowFormat: "format"},
                    {id:25, rowDataField:"data", rowCaption:"row_25", rowFormat: "format"},
                    {id:26, rowDataField:"data", rowCaption:"row_26", rowFormat: "format"},
                    {id:27, rowDataField:"data", rowCaption:"row_27", rowFormat: "format"},
                    {id:28, rowDataField:"data", rowCaption:"row_28", rowFormat: "format"},
                    {id:29, rowDataField:"data", rowCaption:"row_29", rowFormat: "format"},
                    {id:30, rowDataField:"data", rowCaption:"row_30", rowFormat: "format"},
                    {id:31, rowDataField:"data", rowCaption:"row_31", rowFormat: "format"},
                    {id:32, rowDataField:"data", rowCaption:"row_32", rowFormat: "format"},
                    {id:33, rowDataField:"data", rowCaption:"row_33", rowFormat: "format"},
                    {id:34, rowDataField:"data", rowCaption:"row_34", rowFormat: "format"},
                    {id:35, rowDataField:"data", rowCaption:"row_35", rowFormat: "format"},
                    {id:36, rowDataField:"data", rowCaption:"row_36", rowFormat: "format"},
                    {id:37, rowDataField:"data", rowCaption:"row_37", rowFormat: "format"},
                    {id:38, rowDataField:"data", rowCaption:"row_38", rowFormat: "format"},
                    {id:39, rowDataField:"data", rowCaption:"row_39", rowFormat: "format"},
                    {id:40, rowDataField:"data", rowCaption:"row_40", rowFormat: "format"},
                    {id:41, rowDataField:"data", rowCaption:"row_41", rowFormat: "format"},
                    {id:42, rowDataField:"data", rowCaption:"row_42", rowFormat: "format"}
                    ]
            }]

}
export default data